spring.application.name=calorie-ai-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/calorie_ai
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081
